spring:
  datasource:
    url: ${cloud.services.mysql.connection.jdbcurl}
    username: ${cloud.services.mysql.connection.username}
    password: ${cloud.services.mysql.connection.password}
    tomcat:
      test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
